# PUPNET DEPLOY: 1.10.0
# Use: 'pupnet --help conf' for information.

# APP PREAMBLE
AppBaseName = LRReader.Avalonia.Desktop
AppFriendlyName = LRReader
AppId = net.guerra24.lrreader
AppVersionRelease = 1.0.0[1]
AppShortSummary = Client for LANraragi
AppDescription = """
    A feature-complete reader and client for LANraragi
"""
AppLicenseId = GPL-3.0-or-later
AppLicenseFile = 
AppChangeFile = 

# PUBLISHER
PublisherName = Guerra24
PublisherId = net.guerra24
PublisherCopyright = 
PublisherLinkName = GitHub
PublisherLinkUrl = https://github.com/Guerra24/LRReader
PublisherEmail = 
PublisherGpgKeyId = 

# DESKTOP INTEGRATION
DesktopNoDisplay = false
DesktopTerminal = false
DesktopFile = 
StartCommand = 
PrimeCategory = 
MetaFile = app.metainfo.xml
IconFiles = 

# DOTNET PUBLISH
DotnetProjectPath = LRReader.Avalonia.Desktop/LRReader.Avalonia.Desktop.csproj
DotnetPublishArgs = --self-contained true -p:Version=${APP_VERSION} -p:PublishSingleFile=true
DotnetPostPublish = 
DotnetPostPublishOnWindows = 

# PACKAGE OUTPUT
PackageName = LRReader
OutputDirectory = LRReader.Avalonia.Desktop/AppPackages

# APPIMAGE OPTIONS
AppImageArgs = 
AppImageRuntimePath = 
AppImageVersionOutput = false

# FLATPAK OPTIONS
FlatpakPlatformRuntime = org.freedesktop.Platform
FlatpakPlatformSdk = org.freedesktop.Sdk
FlatpakPlatformVersion = 25.08
FlatpakFinishArgs = """
    --socket=x11
"""
FlatpakBuilderArgs = 

# RPM OPTIONS
RpmAutoReq = false
RpmAutoProv = true
RpmRequires = """
    glibc
    libgcc
    ca-certificates
    openssl-libs
    libstdc++
    libicu
    tzdata
    krb5-libs
"""

# DEBIAN OPTIONS
DebianRecommends = """
    libc6
    libgcc-s1
    libgssapi-krb5-2
    libicu72
    libssl3
    libstdc++6
    zlib1g
"""

# WINDOWS SETUP OPTIONS
SetupGroupName = 
SetupAdminInstall = false
SetupCommandPrompt = 
SetupMinWindowsVersion = 10
SetupSignTool = 
SetupSuffixOutput = 
SetupVersionOutput = false
SetupUninstallScript = 

# ZIP OPTIONS
ZipVersionOutput = true