<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishLzmaCompressed>true</PublishLzmaCompressed>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <EnableMsixTooling>true</EnableMsixTooling>
    <MicrosoftWindowsSdkBuildToolsMSIXPackageVersion>1.7.260610101</MicrosoftWindowsSdkBuildToolsMSIXPackageVersion>
    <MicrosoftWindowsSDKBuildToolsPackageVersion>10.0.28000.2705</MicrosoftWindowsSDKBuildToolsPackageVersion>
    <WindowsSdkPackageVersion>10.0.26100.87</WindowsSdkPackageVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableEmbeddedXbf>false</DisableEmbeddedXbf>
    <CsWinRTAotWarningLevel>3</CsWinRTAotWarningLevel>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN;$(DefineConstants)</DefineConstants>
    <ProjectPriFileName>resources.pri</ProjectPriFileName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <MrmPatcherEmbedPri>true</MrmPatcherEmbedPri>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Title>LRReader Installer</Title>
    <Description>LRReader Sideload Installer</Description>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="PublishAotCompressed" Version="1.0.5" Condition="'$(Platform)' == 'x64'" />
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.26100.6" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
    <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="XamlHostingKit.Static" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LRReader.UWP.Servicing\LRReader.UWP.Servicing.csproj" />
  </ItemGroup>

</Project>