name: 'Create SysRoot'
description: 'Ubuntu 18.04'
runs:
  using: "composite"
  steps:
    - name: Create
      shell: bash
      run: |
        docker run -d --name sysroot ubuntu:18.04 sleep infinity
        docker exec -it sysroot apt-get update
        docker exec -it sysroot apt-get install -y build-essential libc6-dev libstdc++-7-dev
        sudo apt-get install -y symlinks
        sudo mkdir -p /opt/sysroot
        sudo chown -R $(whoami):$(whoami) /opt/sysroot
        docker container export sysroot | tar -C /opt/sysroot -xf -
        docker rm -f sysroot
        symlinks -cr /opt/sysroot
